# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59e357b17df04dc4fe7e55c55ddf1ee4ab73dd11ad155c39439d081504949f6df32c5cc15406e4afa05203c3345199fb5e5af7186b3df3319d3ba1ac01982953

test:
  secret_key_base: 0e0121705c4bc651998be49d1b4e066fa7ff37573fc57c173b634e2ee61a7ad9a9df9dff6398391b621c0b411a4c34a381d89bdb35f675f62d0902ced2e8c1f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
